plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework:spring-context:5.3.39'
    implementation 'org.springframework:spring-jdbc:5.3.39'
    implementation 'com.h2database:h2:2.2.224'
    implementation 'org.slf4j:slf4j-api:1.7.36'
    implementation 'ch.qos.logback:logback-classic:1.2.13'
}

application {
    mainClass = 'org.example.App'
    applicationDefaultJvmArgs = ['-Dfile.encoding=UTF-8']
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

java {
    sourceCompatibility = '11'
    targetCompatibility = '11'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
