plugins {
    id 'java'
    id 'application'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework:spring-context:6.2.2'
    implementation 'org.springframework:spring-orm:6.2.2'
    implementation 'org.springframework:spring-tx:6.2.2'

    implementation 'org.hibernate.orm:hibernate-core:6.6.4.Final'
    implementation 'jakarta.persistence:jakarta.persistence-api:3.1.0'

    implementation 'com.zaxxer:HikariCP:5.1.0'
    implementation 'com.h2database:h2:2.2.224'

    implementation 'org.slf4j:slf4j-api:2.0.16'
    implementation 'ch.qos.logback:logback-classic:1.5.12'

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
}

application {
    mainClass = 'ru.bsuedu.cad.lab.app.App'
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks.named('test') {
    useJUnitPlatform()
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}